/*
 * File: app/store/TipoCasillaStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TipoCasillaStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.TipoCasilla'
    ],

    config: {
        data: [
            {
                id: '1',
                desc: 'Basica'
            },
            {
                id: '2',
                desc: 'Contigua'
            },
            {
                id: '3',
                desc: 'Ext. Contigua'
            },
            {
                id: '4',
                desc: 'Especial'
            }
        ],
        model: 'MyApp.model.TipoCasilla',
        storeId: 'tipoCasillaStore'
    }
});